version: '3.8'

services:
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata_ids
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
    command: -i eth0 -S /var/lib/suricata/rules/local.rules
    volumes:
      - ./rules/local.rules:/var/lib/suricata/rules/local.rules
      - ./logs:/var/log/suricata
    restart: always